-- CreateTable
CREATE TABLE "Odekon_Catalog" (
    "objid_new_1_1" INTEGER NOT NULL,
    "agcnum" DOUBLE PRECISION NOT NULL,
    "sdss_ra" DOUBLE PRECISION,
    "sdss_dec" DOUBLE PRECISION,
    "sdss_z" DOUBLE PRECISION,
    "ocra" DOUBLE PRECISION,
    "ocdec" DOUBLE PRECISION,
    "hisrc" TEXT,
    "hicode" DOUBLE PRECISION,
    "sdsscode" TEXT,
    "photoid" DOUBLE PRECISION,
    "spectid" DOUBLE PRECISION,
    "name" TEXT,
    "hira" DOUBLE PRECISION,
    "hidec" DOUBLE PRECISION,
    "v21" DOUBLE PRECISION,
    "w50" DOUBLE PRECISION,
    "werr" DOUBLE PRECISION,
    "flux" DOUBLE PRECISION,
    "fluxerr" DOUBLE PRECISION,
    "snratio" DOUBLE PRECISION,
    "rms_detection" DOUBLE PRECISION,
    "dist_1" DOUBLE PRECISION,
    "loghimass_1" DOUBLE PRECISION,
    "detcode" DOUBLE PRECISION,
    "petro_mag_r" DOUBLE PRECISION,
    "petro_mag_g" DOUBLE PRECISION,
    "cmodelmag_g" DOUBLE PRECISION,
    "cmodelmagerr_g" DOUBLE PRECISION,
    "modelmag_g" DOUBLE PRECISION,
    "petro_mag_i" DOUBLE PRECISION,
    "cmodelmag_i" DOUBLE PRECISION,
    "cmodelmagerr_i" DOUBLE PRECISION,
    "modelmag_i" DOUBLE PRECISION,
    "expab_g" DOUBLE PRECISION,
    "devab_g" DOUBLE PRECISION,
    "nvote" DOUBLE PRECISION,
    "elliptical" DOUBLE PRECISION,
    "spiralclock" DOUBLE PRECISION,
    "spiralanticlock" DOUBLE PRECISION,
    "spiral" DOUBLE PRECISION,
    "edgeon" DOUBLE PRECISION,
    "dontknow" DOUBLE PRECISION,
    "merger" DOUBLE PRECISION,
    "dr7objid" DOUBLE PRECISION,
    "isoa_r" DOUBLE PRECISION,
    "yang_igal" DOUBLE PRECISION,
    "nyuvagcid" DOUBLE PRECISION,
    "yang_ra" DOUBLE PRECISION,
    "yang_dec" DOUBLE PRECISION,
    "yang_z" DOUBLE PRECISION,
    "grpid" DOUBLE PRECISION,
    "brightest" DOUBLE PRECISION,
    "most_massive" DOUBLE PRECISION,
    "grp_ra" DOUBLE PRECISION,
    "grp_dec" DOUBLE PRECISION,
    "grp_z" DOUBLE PRECISION,
    "grp_l" DOUBLE PRECISION,
    "grp_mstar" DOUBLE PRECISION,
    "grp_massl" DOUBLE PRECISION,
    "grp_massm" DOUBLE PRECISION,
    "no_in_group" DOUBLE PRECISION,
    "yang_separation" DOUBLE PRECISION,
    "yang_zdiff" DOUBLE PRECISION,
    "czdiff" DOUBLE PRECISION,
    "proximity" DOUBLE PRECISION,
    "nnd3" DOUBLE PRECISION,
    "nnd3to10" DOUBLE PRECISION,
    "envcode1" DOUBLE PRECISION,
    "envcode2" DOUBLE PRECISION,
    "envcode2b" DOUBLE PRECISION,
    "envcode3" DOUBLE PRECISION,
    "dbackbone_old" DOUBLE PRECISION,
    "dffpecz" DOUBLE PRECISION,
    "dffgroupz" DOUBLE PRECISION,
    "ebmv" DOUBLE PRECISION,
    "dist" DOUBLE PRECISION,
    "ag" DOUBLE PRECISION,
    "ai" DOUBLE PRECISION,
    "ggal" DOUBLE PRECISION,
    "igal" DOUBLE PRECISION,
    "gshao" DOUBLE PRECISION,
    "ishao" DOUBLE PRECISION,
    "gmi_shao" DOUBLE PRECISION,
    "loghimass" DOUBLE PRECISION,
    "angledistance" DOUBLE PRECISION,
    "d25" DOUBLE PRECISION,
    "logd25corrected" DOUBLE PRECISION,
    "hidefd25" DOUBLE PRECISION,
    "log_li" DOUBLE PRECISION,
    "log_mstar_taylor" DOUBLE PRECISION,
    "avg_rms" DOUBLE PRECISION,
    "rms_est" DOUBLE PRECISION,
    "skew" DOUBLE PRECISION,
    "rms" DOUBLE PRECISION,
    "cosincl" DOUBLE PRECISION,
    "wmxi" DOUBLE PRECISION,
    "wmx" DOUBLE PRECISION,
    "wmcorrint" DOUBLE PRECISION,
    "wm50" DOUBLE PRECISION,
    "slim" DOUBLE PRECISION,
    "loghimassorlim" DOUBLE PRECISION,
    "massratorlim" DOUBLE PRECISION,
    "hideforlim" DOUBLE PRECISION,
    "detectionstatus" INTEGER,
    "faint_end" DOUBLE PRECISION,
    "blue_cloud" DOUBLE PRECISION,
    "red_sequence" DOUBLE PRECISION,
    "zgroup" DOUBLE PRECISION,

    PRIMARY KEY ("agcnum")
);

-- CreateIndex
CREATE UNIQUE INDEX "Odekon_Catalog.agcnum_unique" ON "Odekon_Catalog"("agcnum");
