export const TULLY_GROUP_LOOKUP = 'TULLY_GROUP_LOOKUP';
export const SDSS_OPTICAL_LOOKUP = 'SDSS_OPTICAL_LOOKUP';
export const SDSS_DERIVED_LOOKUP = 'SDSS_DERIVED_LOOKUP';
export const TULLY_ENVIRONMENT_LOOKUP = 'TULLY_ENVIRONMENT_LOOKUP';