-- CreateTable
CREATE TABLE "Tully_Environment" (
    "orig_src_name" TEXT NOT NULL,
    "hisrc_name" TEXT NOT NULL,
    "agcnr" INTEGER NOT NULL,
    "name" TEXT,
    "radeg_hi" DOUBLE PRECISION NOT NULL,
    "decdeg_hi" DOUBLE PRECISION NOT NULL,
    "radeg_oc" DOUBLE PRECISION NOT NULL,
    "decdeg_oc" DOUBLE PRECISION NOT NULL,
    "radeg_use" DOUBLE PRECISION NOT NULL,
    "decdeg_use" DOUBLE PRECISION NOT NULL,
    "vhelio" INTEGER NOT NULL,
    "errv" INTEGER NOT NULL,
    "w50" INTEGER NOT NULL,
    "err_wtot" INTEGER NOT NULL,
    "err_wstat" INTEGER NOT NULL,
    "w20" INTEGER NOT NULL,
    "hiflux" DOUBLE PRECISION NOT NULL,
    "errflux" DOUBLE PRECISION NOT NULL,
    "snr" DOUBLE PRECISION NOT NULL,
    "rms" DOUBLE PRECISION NOT NULL,
    "dist" DOUBLE PRECISION NOT NULL,
    "log_msun" DOUBLE PRECISION NOT NULL,
    "hicode" INTEGER NOT NULL,
    "phot_code" TEXT NOT NULL,
    "agc" INTEGER NOT NULL,
    "objid" DOUBLE PRECISION NOT NULL,
    "parentid" DOUBLE PRECISION NOT NULL,
    "spec_objid" DOUBLE PRECISION NOT NULL,
    "ra" DOUBLE PRECISION NOT NULL,
    "dec" DOUBLE PRECISION NOT NULL,
    "model_mag_u" DOUBLE PRECISION NOT NULL,
    "model_mag_g" DOUBLE PRECISION NOT NULL,
    "model_mag_r" DOUBLE PRECISION NOT NULL,
    "model_mag_i" DOUBLE PRECISION NOT NULL,
    "model_mag_z" DOUBLE PRECISION NOT NULL,
    "model_mag_err_u" DOUBLE PRECISION NOT NULL,
    "model_mag_err_g" DOUBLE PRECISION NOT NULL,
    "model_mag_err_r" DOUBLE PRECISION NOT NULL,
    "model_mag_err_i" DOUBLE PRECISION NOT NULL,
    "model_mag_err_z" DOUBLE PRECISION NOT NULL,
    "c_model_mag_u" DOUBLE PRECISION NOT NULL,
    "c_model_mag_g" DOUBLE PRECISION NOT NULL,
    "c_model_mag_r" DOUBLE PRECISION NOT NULL,
    "c_model_mag_i" DOUBLE PRECISION NOT NULL,
    "c_model_mag_z" DOUBLE PRECISION NOT NULL,
    "c_model_mag_err_u" DOUBLE PRECISION NOT NULL,
    "c_model_mag_err_g" DOUBLE PRECISION NOT NULL,
    "c_model_mag_err_r" DOUBLE PRECISION NOT NULL,
    "c_model_mag_err_i" DOUBLE PRECISION NOT NULL,
    "c_model_mag_err_z" DOUBLE PRECISION NOT NULL,
    "petro_mag_u" DOUBLE PRECISION NOT NULL,
    "petro_mag_g" DOUBLE PRECISION NOT NULL,
    "petro_mag_r" DOUBLE PRECISION NOT NULL,
    "petro_mag_i" DOUBLE PRECISION NOT NULL,
    "petro_mag_z" DOUBLE PRECISION NOT NULL,
    "petro_mag_err_u" DOUBLE PRECISION NOT NULL,
    "petro_mag_err_g" DOUBLE PRECISION NOT NULL,
    "petro_mag_err_r" DOUBLE PRECISION NOT NULL,
    "petro_mag_err_i" DOUBLE PRECISION NOT NULL,
    "petro_mag_err_z" DOUBLE PRECISION NOT NULL,
    "petro_rad_u" DOUBLE PRECISION NOT NULL,
    "petro_rad_g" DOUBLE PRECISION NOT NULL,
    "petro_rad_r" DOUBLE PRECISION NOT NULL,
    "petro_rad_i" DOUBLE PRECISION NOT NULL,
    "petro_rad_z" DOUBLE PRECISION NOT NULL,
    "petror50_g" DOUBLE PRECISION NOT NULL,
    "petror50_r" DOUBLE PRECISION NOT NULL,
    "petror50_i" DOUBLE PRECISION NOT NULL,
    "petror90_g" DOUBLE PRECISION NOT NULL,
    "petror90_r" DOUBLE PRECISION NOT NULL,
    "petror90_i" DOUBLE PRECISION NOT NULL,
    "extinction_u" DOUBLE PRECISION NOT NULL,
    "extinction_g" DOUBLE PRECISION NOT NULL,
    "extinction_r" DOUBLE PRECISION NOT NULL,
    "extinction_i" DOUBLE PRECISION NOT NULL,
    "extinction_z" DOUBLE PRECISION NOT NULL,
    "expab_g" DOUBLE PRECISION NOT NULL,
    "expab_r" DOUBLE PRECISION NOT NULL,
    "expab_i" DOUBLE PRECISION NOT NULL,
    "exp_mag_g" DOUBLE PRECISION NOT NULL,
    "exp_mag_r" DOUBLE PRECISION NOT NULL,
    "exp_mag_i" DOUBLE PRECISION NOT NULL,
    "flags_u" DOUBLE PRECISION NOT NULL,
    "flags_g" DOUBLE PRECISION NOT NULL,
    "flags_r" DOUBLE PRECISION NOT NULL,
    "flags_i" DOUBLE PRECISION NOT NULL,
    "flags_z" DOUBLE PRECISION NOT NULL,
    "flags" DOUBLE PRECISION NOT NULL,
    "lnlexp_r" DOUBLE PRECISION NOT NULL,
    "lnldev_r" DOUBLE PRECISION NOT NULL,
    "type" DOUBLE PRECISION NOT NULL,
    "frac_dev_g" DOUBLE PRECISION NOT NULL,
    "frac_dev_r" DOUBLE PRECISION NOT NULL,
    "frac_dev_i" DOUBLE PRECISION NOT NULL,
    "exp_rad_g" DOUBLE PRECISION NOT NULL,
    "exp_rad_r" DOUBLE PRECISION NOT NULL,
    "exp_rad_i" DOUBLE PRECISION NOT NULL,
    "skydistdeg2" DOUBLE PRECISION NOT NULL,
    "skdistarcsec" DOUBLE PRECISION NOT NULL,
    "ocfromsdssarcseconds" DOUBLE PRECISION NOT NULL,

    PRIMARY KEY ("agcnr")
);

-- CreateIndex
CREATE UNIQUE INDEX "Tully_Environment.agcnr_unique" ON "Tully_Environment"("agcnr");
